question_data = [{"category": "Vehicles", "type": "boolean", "difficulty": "hard",
                  "question": "In 1993 Swedish car manufacturer Saab experimented with replacing the steering wheel with a joystick in a Saab 9000.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "hard",
                  "question": "Japan was part of the Allied Powers during World War I.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
                  "question": "You can calculate Induced Voltage using: &epsilon; =-N * (d&Phi;B)\/(d)",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
                  "question": "If you could fold a piece of paper in half 50 times, its&#039; thickness will be 3\/4th the distance from the Earth to the Sun.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "hard",
                  "question": "Throughout the entirety of &quot;Dragon Ball Z&quot;, Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                  "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "hard",
                  "question": "The Battle of Trafalgar took place on October 23rd, 1805",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "hard",
                  "question": "The board game Go has more possible legal positions than the number of atoms in the visible universe.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "hard",
                  "question": "In the &quot;To Love-Ru&quot; series, Peke is considered a female robot.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "hard",
                  "question": "The two largest ethnic groups of Belgium are Flemish and Walloon. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
